// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockrepository

import (
	context "context"

	converter "github.com/defany/chat-server/app/internal/converter"
	mock "github.com/stretchr/testify/mock"

	model "github.com/defany/chat-server/app/internal/model"
)

// MockChat is an autogenerated mock type for the Chat type
type MockChat struct {
	mock.Mock
}

type MockChat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChat) EXPECT() *MockChat_Expecter {
	return &MockChat_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, chat
func (_m *MockChat) Create(ctx context.Context, chat model.Chat) (uint64, error) {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Chat) (uint64, error)); ok {
		return rf(ctx, chat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Chat) uint64); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Chat) error); ok {
		r1 = rf(ctx, chat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChat_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChat_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - chat model.Chat
func (_e *MockChat_Expecter) Create(ctx interface{}, chat interface{}) *MockChat_Create_Call {
	return &MockChat_Create_Call{Call: _e.mock.On("Create", ctx, chat)}
}

func (_c *MockChat_Create_Call) Run(run func(ctx context.Context, chat model.Chat)) *MockChat_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Chat))
	})
	return _c
}

func (_c *MockChat_Create_Call) Return(_a0 uint64, _a1 error) *MockChat_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChat_Create_Call) RunAndReturn(run func(context.Context, model.Chat) (uint64, error)) *MockChat_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockChat) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChat_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChat_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockChat_Expecter) Delete(ctx interface{}, id interface{}) *MockChat_Delete_Call {
	return &MockChat_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChat_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockChat_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockChat_Delete_Call) Return(_a0 error) *MockChat_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockChat_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, input
func (_m *MockChat) SendMessage(ctx context.Context, input converter.SendMessageInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, converter.SendMessageInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChat_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockChat_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input converter.SendMessageInput
func (_e *MockChat_Expecter) SendMessage(ctx interface{}, input interface{}) *MockChat_SendMessage_Call {
	return &MockChat_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, input)}
}

func (_c *MockChat_SendMessage_Call) Run(run func(ctx context.Context, input converter.SendMessageInput)) *MockChat_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(converter.SendMessageInput))
	})
	return _c
}

func (_c *MockChat_SendMessage_Call) Return(_a0 error) *MockChat_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChat_SendMessage_Call) RunAndReturn(run func(context.Context, converter.SendMessageInput) error) *MockChat_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChat creates a new instance of MockChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChat {
	mock := &MockChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
